version: '3.1'
services:
  proxy:
    build: proxy
    image: ngrefarch/fm-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    container_name: fabric_proxy

  web:
    build: web
    image: ngrefarch/fm-web
    environment:
      - BACKEND_ENDPOINT_URL=http://localhost/backend
    ports:
      - "81:80"
    depends_on:
      - backend
    volumes:
      - ./web/app:/app
    container_name: fabric_web

  backend:
    build: backend
    image: ngrefarch/fm-backend
    ports:
      - "82:80"
    volumes:
      - ./backend/app:/usr/src/app
    container_name: fabric_be
