version: '3.1'
services:
  proxy:
    build:
      context: proxy/
      args:
        - CERT_FILE_NAME=certificate.pem
        - KEY_FILE_NAME=key.pem
    image: fabric-model/proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    container_name: fabric_proxy

  web:
    build:
      context: web/
      args:
        - CERT_FILE_NAME=certificate.pem
        - KEY_FILE_NAME=key.pem
    image: fabric-model/web
    environment:
      - BACKEND_ENDPOINT_URL=http://localhost/backend
    ports:
      - "81:80"
    depends_on:
      - backend
    volumes:
      - ./web/app:/app
    container_name: fabric_web

  backend:
    build:
      context: backend/
      args:
        - CERT_FILE_NAME=certificate.pem
        - KEY_FILE_NAME=key.pem
    image: fabric-model/backend
    ports:
      - "82:80"
    volumes:
      - ./backend/app:/usr/src/app
    container_name: fabric_be
